/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import com.sun.org.apache.xml.internal.security.c14n.Canonicalizer;
import org.junit.Assert;
import org.junit.Test;
import static org.junit.Assert.*;

public class CanonicaliserTest {

    @Test public void mapsUniqueCharacterStringToCanocialForm() {
        String canonical = new Canonicaliser().convert("bcdef");

        assertEquals("abcde", canonical);
    }

    @Test public void mapsDuplicateCharacterStringToCanocialForm() {
        String canonical = new Canonicaliser().convert("bbb");

        assertEquals("aaa", canonical);
    }

    @Test public void mapsMixedCharacterStringToCanocialForm() {
        String canonical = new Canonicaliser().convert("xoxbbbaco");

        assertEquals("abacccdeb", canonical);
    }
}
